# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-21 01:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20161220_1603'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tags',
            field=models.TextField(blank=True, max_length=50, verbose_name='tags'),
        ),
    ]
